#!/usr/bin/env node
/**
 * Rewrites HTML script src references to point at content-hashed *.min.js filenames.
 * Reads the manifest generated by build.js (scripts/asset-manifest.json).
 *
 * Handles all existing patterns:
 *   /assets/login.min.js?v=20260416   → /assets/login.{hash8}.min.js
 *   /assets/login.oldsha1.min.js       → /assets/login.{hash8}.min.js
 *   /vendor/sentry.min.js?v=xxx        → /vendor/sentry.{hash8}.min.js
 *
 * Only touches files listed in HTML_FILES — ignores demo/, backups, etc.
 * Run: node scripts/update-refs.js  (automatically called by npm run build)
 */

const fs   = require('fs');
const path = require('path');

const ROOT          = path.resolve(__dirname, '..');
const MANIFEST_PATH = path.join(__dirname, 'asset-manifest.json');

if (!fs.existsSync(MANIFEST_PATH)) {
  console.error('❌  asset-manifest.json not found. Run `node scripts/build.js` first.');
  process.exit(1);
}

const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));

// HTML files to update (relative to project root)
const HTML_FILES = [
  'index.html',
  'acesso/index.html',
  'login/index.html',
  'cadastro/index.html',
  'demo/index.html',
  'en/index.html',
  'es/index.html',
  'faq/index.html',
  'soporte/index.html',
  'suporte/index.html',
  'painel-parceiro/index.html',
  'painel-cliente/app/index.html',
];

let totalFiles        = 0;
let totalReplacements = 0;

for (const rel of HTML_FILES) {
  const file = path.join(ROOT, rel);
  if (!fs.existsSync(file)) continue;

  let content      = fs.readFileSync(file, 'utf8');
  let replacements = 0;

  for (const [srcRel, hashedRel] of Object.entries(manifest)) {
    // srcRel    = 'assets/login.js'
    // hashedRel = 'assets/login.abc12345.min.js'
    const baseName  = path.basename(srcRel, '.js');           // 'login'
    const dirPart   = srcRel.replace(/\\/g, '/').split('/').slice(0, -1).join('/'); // 'assets'
    const newPath   = '/' + hashedRel.replace(/\\/g, '/');   // '/assets/login.abc12345.min.js'

    // Escape special regex chars in dir / baseName (unlikely but safe)
    const eDir  = dirPart.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const eBase = baseName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

    // Matches any of:
    //   /assets/login.min.js              (no query string)
    //   /assets/login.min.js?v=20260416   (old query-string versioning)
    //   /assets/login.abc12345.min.js     (already hashed — possibly different hash)
    const re = new RegExp(
      `/${eDir}/${eBase}(?:\\.[a-f0-9]{8})?\\.min\\.js(?:\\?[^"'\\s>]*)?`,
      'g'
    );

    const before = content;
    content = content.replace(re, newPath);
    if (content !== before) replacements++;
  }

  if (replacements > 0) {
    fs.writeFileSync(file, content, 'utf8');
    console.log(`[ok]  ${rel.padEnd(30)} (${replacements} ref${replacements !== 1 ? 's' : ''} updated)`);
    totalFiles++;
    totalReplacements += replacements;
  }
}

console.log(`\nDone. ${totalFiles} file${totalFiles !== 1 ? 's' : ''}, ${totalReplacements} reference${totalReplacements !== 1 ? 's' : ''} updated.`);
